### ISSUE TITLE
Question about jsonb

### ISSUE THREAD

**Issue by nickmcdonnough** [Moove-it/swaggard#10]
One of the models in my application has an attribute with type jsonb. The serializer for that model returns several attributes including the one that is of jsonb type. How do I document this with Swaggard? There is no object type as far as I can tell so I'm at a bit of a loss.

Thanks.

**Comment by adrian-gomez** [comment]
Do you have an example of the field? You can create an new serializer for that field (given it always has the same fields) and use it just for documentation:

```
# @attr [DefaultsSerializer] defaults
class CarSerializer < ActiveModel::Serializer
  attribute :defaults # jsonb field
end

# @attr [string] color
# @attr [integer] wheels
class DefaultsSerializer < ActiveModel::Serializer
end
```

or you can actually wrap the jsonb in a ruby object that responds to the keys on the json:

```
class Defaults
  def initialize(jsonb)
    @jsonb = jsonb
  end

  def color
    @jsonb['color']
  end

  def wheels
    @jsonb['wheels']
  end
end

# @attr [DefaultsSerializer] defaults
class CarSerializer < ActiveModel::Serializer
  has_one :defaults, serializer: DefaultsSerializer

  def defaults
    @defaults ||= Defaults.new(object.defaults)
  end
end

# @attr [string] color
# @attr [integer] wheels
class DefaultsSerializer < ActiveModel::Serializer
    attribute :color
    attribute :wheels
end
```

Those are the options I can think of the top of my head, if you give me more info I can try to think on something else.

**Comment by nickmcdonnough** [comment]
Sorry for such a late reply. I ended up going with something similar to what you suggested here. Thanks a lot Adrian!
