### ISSUE TITLE
Support for Rails 5

### ISSUE THREAD

**Issue by huascar** [Moove-it/swaggard#15]
Swaggard is a util gem but doesn´t support for Rails 5

**Comment by OleMchls** [comment]
I wonder what's missing to make it rails 5 compat? Any specific tasks one can help with? @maintainers

**Comment by edvardm** [comment]
This was a very ugly hack, but so far it seems to work with Rails 5 using this patch:

```
diff --git a/lib/swaggard/parsers/routes.rb b/lib/swaggard/parsers/routes.rb
index d4767c2..1652402 100644
--- a/lib/swaggard/parsers/routes.rb
+++ b/lib/swaggard/parsers/routes.rb
@@ -33,7 +33,7 @@ module Swaggard
       end

       def route_verb(route)
-        route.verb.source.gsub(/[$^]/, '')
+        route.verb.gsub(/[$^]/, '')
       end

       def route_path(route)
@@ -51,4 +51,4 @@ module Swaggard

     end
   end
-end
\ No newline at end of file
+end
diff --git a/swaggard.gemspec b/swaggard.gemspec
index 8517cd4..c775662 100644
--- a/swaggard.gemspec
+++ b/swaggard.gemspec
@@ -16,7 +16,7 @@ Gem::Specification.new do |s|
   s.files = Dir['{app,config,public,lib}/**/*'] + ['MIT-LICENSE', 'Rakefile', 'README.md']
   s.test_files = Dir['spec/**/*']

-  s.add_dependency 'rails', '~> 4.0'
+  s.add_dependency 'rails', '>= 4.0'
   s.add_dependency 'sass-rails'

   s.add_development_dependency 'rspec'
```

that is, by just using more lenient dependency, and removing `#source` call for String. 
I could not quickly find out /w Google what that `#source` was used for.

**Comment by julioalucero** [comment]
I did the same and I works (on rails-api 5) to me

Also I added on config/application.rb `require "sprockets/railtie"`

**Comment by adrian-gomez** [comment]
Hi guys, thanks a lot for your help. I'll working on adding support for rails 5 and other smalls issues soon. I have a little more time to work on this now

**Comment by adrian-gomez** [comment]
@julioalucero @EdvardM @nesQuick @huascar I have uploaded #19 if any of you can try that one and let me know if it works ok on your app that would be great.
As soon as I get confirmation (or in a few days without response) I'll release a new version with it.

BTW all the comments on this thread helped in creating that PR, thanks a lot!

**Comment by adrian-gomez** [comment]
I'm closing this one as the #19 has been merged
