### ISSUE TITLE
Comment paragraphs with newlines (a la 80-char limit on line length) causes superfluous newlines when documentation is viewed

### ISSUE THREAD

**Issue by contingencyplan** [Moove-it/swaggard#2]
NOTE: I am still new to Ruby / Rails and Javascript development, so please
take these notes with a grain of salt.

According to the Ruby style guide, lines should be limited to 80 characters
(https://github.com/bbatsov/ruby-style-guide#80-character-limits). We hold to
this standard both for code and for comments, so a paragraph in a class or
method's documentation may span multiple lines.

The problem arises when we view our Swaggard-generated API 
documentation --- the generated documentation itself follows the 80-char line
length, rather than being word-wrapped according to the size of the text area
as expected. This occurs in both the Swaggard implementation of swagger-ui and
in swagger_engine (https://github.com/batdevis/swagger_engine).

I believe that this is caused by two lines of code:
-  https://github.com/moove-it/swaggard/blob/master/lib/swaggard/swagger/operation.rb#L24
  -  Because the documentation already contains newlines, this causes two
    `\n` characters to appear in the JSON. The Markdown engine interprets
    this to indicate separate paragraphs, causing each line in the
    generated HTML to be wrapped in `<p>` tags.
  -  This affects **both** the swagger_engine and the Swaggard
    implementations of swagger-ui, as this impacts the JSON file that is
    used to display the documentation.
  -  Joining the lines on the empty string appears to remedy this problem;
    if so, then this is a necessary and sufficient solution for viewing
    the documentation in swagger_engine. However, it is **not** a sufficient
    solution for the Swaggard viewer (though still necessary); see below.
-  https://github.com/moove-it/swaggard/blob/master/app/assets/javascripts/swaggard/swagger-ui.js#L1185
  -  From what I can tell, this line is replacing every newline with 
    `<br />` **before** the Markdown engine processes the text,
    circumventing the Markdown rules for handling single vs. multiple
    newline characters.
  -  It does not appear that either swagger-ui or swagger_engine implement
    this logic, so only the Swaggard implementation of swagger-ui is
    affected.
  -  Commenting out this conditional appears a necessary (and, combined
    with the above change, sufficient) change to solve the problem with
    the Swaggard viewer. 

I will submit a pull request with these two changes made. From what I can
tell, they should not negatively impact anything else in the code, but I am
obviously not as familiar with the code base as you are. :-)

On one final note, it may be worthwhile to document the expected formatting of
comments for classes, methods, etc. For example, it appears that controller
classes should only be given a single comment line, as any additional
paragraphs are concatenated into the description of the API section.
Furthermore, the documentation for a single method appears to expect a single
initial line which is taken as the summary, with all additional lines taken as
the "Implementation Notes." I wouldn't consider these to be problems or
errors per se, but it would be good to have these expectations documented for
users of this project.

(Also, thank you for creating this --- I definitely like the combination of
YARD-style documentation and the Swagger presentation UI!)

**Comment by adrian-gomez** [comment]
Hi thanks for the PR (and sorry for the delayed response).
As I mentioned in the PR we use a clean version of the swagger-ui js (in order to be able to keep it up to date without having to apply a bunch of patches every time). If we can find a way of adding stuff to it without actually touching the original js then I'm cool with that. Otherwise we should first make a PR on swagger-ui and then update the version we use here.

I think that swagger_engine uses the same approach of using an unmodified version of swagger-ui thats why you also see the problem there.

Thanks for the kind words :D it's always nice to hear that this is useful for someone else.

**Comment by adrian-gomez** [comment]
@contingencyplan Hi I have uploaded to a new version that brings swagger-ui to the latest version, you can give it a try and see if that fixes the style issues.
