### ISSUE TITLE
Configure for SSL only sites?

### ISSUE THREAD

**Issue by house9** [Moove-it/swaggard#20]
This is working great for localhost, but when I push it to staging which only allows SSL connections it still makes requests to http.

I tried setting `api_base_path` to:

`config.api_base_path = 'https://api.example.com'`

But it seems like `api_base_path` is getting appended to the current host:

`http://localhost:3000https://api.example.com/widgets`

Any ideas? 

BTW: I am currently using the rails-5 branch #15, I doubt that is causing the issue - I will try to install current stable branch and double check that as well.

**Comment by house9** [comment]
I used this as a workaround for now

`Swaggard.configuration.instance_variable_set(:@schemes, [:https]) if Rails.env.staging?`

Ideally #12 would be merged then it could be as simple as 

```
Swaggard.configure do |config|
  config.schemes = [:https] if Rails.env.staging?
end
```

**Comment by adrian-gomez** [comment]
@house9  Thanks for the report and solution, I have pushed a fix for it to master. I'm also going to merge the rails 5 branch and build a new version.

I'll also take a look at the api base path issue as it should not behave like that.

Also for future reference it seems that your rails app is not aware of what your domain is, if its behind a reverse proxy (nginx or apache) you need to indicate that you want the domain (and the schema) forwarded to your rails app.
For nginx this would be done with:

```
       .....
        proxy_pass your-rails-app-upstream;
        
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Ssl on;
        ......
```

**Comment by house9** [comment]
Thanks @adrian-gomez - I am using the latest version of gem now (0.5.0) and everything looks good!

`schemes` config and rails 5 💥
