### ISSUE TITLE
Swaggard hash param usage on Rails 5

### ISSUE THREAD

**Issue by ghost** [Moove-it/swaggard#21]
Hello,

I'm not sure how to correctly use the hash feature. Params for my controllers have to be inside of a hash, like so {"talent"=>{"name":"Some Person"}}, where talent is the name of the hash. I'm running rails 5. The comments I have for the create method look like this:

#Creates a talent record
  #@body_parameter [hash] talent

1) The resultant swagger interface looks weird. it looks like this:
![screen shot 2016-12-13 at 11 24 09 am](https://cloud.githubusercontent.com/assets/6932894/21155359/b7ac41f8-c126-11e6-944e-0ee965c9b384.png)

Notice the "dash" signs in place of a body field. How do I get the body to show?

2) On the right hand side, I'd like the talent hash to be populated with keys and values. Is there a way to currently achieve that? I tried a few tricks, but couldn't get the "name":"Some Person" key-value pair to show up there.

Thank you!

**Comment by adrian-gomez** [comment]
There is a way but its not pretty, basically you need to tell swaggard from where to get the information from.

On your controller:
```
#Creates a talent record
#@body_parameter [Api::Input::TalentForCreation] talent
```

then in `api/input/talent_for_creation.rb`
```
@attr [string] name
class Api::Input::TalentForCreation; end
```

in `config/initializers/swaggard.rb`
```
Swaggard.configure do |config|
  ...
  config.models_paths = %W[#{Rails.root}/api/input/**/*.rb]
  ...
end
```

Note that the path or the class name can be anything its just an empty class that holds the documentation for your input models.

If you have a different idea of how to archive what you need let me know and maybe we can try it out.

Another option would be to receive the params bare, as in not inside a `talent` key.

**Comment by adrian-gomez** [comment]
also for the issue of not being able to edit the json by hand I will release a new version that has the option to disable the json editor and replaces it with a simple text box that you can edit by hand

**Comment by ghost** [comment]
Hi Adrian,

Thanks for such a prompt response! I tried your first suggestion. And I get a Syntax error in talent_for_creation.rb ([warn]: Syntax error in `talent_for_creation.rb`:(1,19): syntax error, unexpected tidentifier, expecting end-of-input). So I tried removing the semicolon, and it was the same. I put the semicolon back in and this is what the swagger ui looks like right now (it loads in spite of the syntax error).


![screen shot 2016-12-13 at 12 15 41 pm](https://cloud.githubusercontent.com/assets/6932894/21157377/ef2981de-c12d-11e6-9c24-8747cf47362d.png)



Also, this is my swaggard.rb initializer configuration:
 Swaggard.configure do |config|
   config.api_version = '0.1'
   config.api_base_path = "/"
   config.default_content_type = 'application/json'
   config.models_paths = %W[#{Rails.root}/api/input/**/*.rb]
   config.api_formats = [:json]
   config.api_path = "/"
   config.host = "localhost:3000"
   config.doc_base_path = '/'
 end

Any idea on what I'm doing wrong?

Thanks!

**Comment by adrian-gomez** [comment]
Hey when I posted the example I missed the `#` symbol on `api/input/talent_for_creation.rb`, it should be:
```
# @attr [string] name
class Api::Input::TalentForCreation; end
```

**Comment by ghost** [comment]
Can't believe I missed that. This works now, thanks Adrian!

**Comment by adrian-gomez** [comment]
np, glad it works for you now!

I'm closing this out

**Comment by sridharsgithub** [comment]
Hi Adrian,

Sorry to pile on top of this. The workaround you provided works great. However, if I want to have nested hash, how would I go about doing that? 

For example: 
```
{
  talent : {
    name : <name>,
    address : {
      address_1: <address_1>,
      address_2: <address_2>,
      city: <city>
    }
  }
}
```

In this case, `address` is a nested hash. Similar to `api/input/talent_for_creation.rb`, I created an other file had the details of this address with a class name Api::Input::TalentAddress and added `#@body_parameter [Api::Input::TalentAddress] address` to `talent_for_creation.rb`. But that did not help. 

Any pointers on how to solve this would be great.

Thanks.

**Comment by adrian-gomez** [comment]
the `*_parameter` is only for the controller layer, for the models you should only use `@attr`.
In your case it would be:
```
# @attr [Api::Input::TalentAddress] address
```

**Comment by sridharsgithub** [comment]
Awesome. That worked. Thank you very much for your quick response.
