### ISSUE TITLE
How to deal with JSON root keys?

### ISSUE THREAD

**Issue by ariejan** [Moove-it/swaggard#23]
Case in point, my serializer returns JSON with a root key, because I'm using the ActiveModel Serializers JSON adapter:

```ruby
ActiveModelSerializers.config.adapter = :json
```

The `PingsController#ping` action:

```ruby
class PingsController < BaseController

  # Responds to pings
  #
  # @response_class PingResponseSerializer
  def ping
    @ping_response = PingResponse.new
    render json: @ping_response
  end
end
```

This is my `PingResponseSerializer`:

```ruby
# @attr [string] text
# @attr [string] status
class PingResponseSerializer < ActiveModel::Serializer
  attribute(:text) { "PONG" }
  attribute(:status) { "ok" }
end
```

Which results in the following JSON output:

```json
{
  "ping_response": {
    "text": "PONG",
    "status": "ok"
  }
}
```

However, this is the _example output_:

```json
{
  "text": "string",
  "status": "string"
}
```

Question: how do I get swagger/swaggard to understand the JSON root key?

**Comment by adrian-gomez** [comment]
Hi @ariejan sorry for the late reply, at the moment the only way to solve this is to use an intermediate serializer, that has the root key and points to the actual serializer.

`PingResponseSerializer`:
```
# @attr [PingResponseBodySerializer] ping_response
class PingResponseSerializer < ActiveModel::Serializer
  has_one :ping_response, serializer: 'PingResponseBodySerializer'

  def ping_response
    object
  end
end
```

`PingResponseBodySerializer`:
```
# @attr [string] text
# @attr [string] status
class PingResponseBodySerializer < ActiveModel::Serializer
  attribute(:text) { "PONG" }
  attribute(:status) { "ok" }
end
```

That would yield the results you want but its quite ugly, I'm open to suggestions of how this could be improved maybe by using an annotation either on the controller or the serializer

**Comment by adrian-gomez** [comment]
@ariejan support for this has been added on #27 you can now do
`@response_root` on your controller
