### ISSUE TITLE
Question: Is it possible to add a UUID definition type?

### ISSUE THREAD

**Issue by schinery** [Moove-it/swaggard#34]
All objects returned by my API I'm have UUIDs for their IDs, and I am wondering if there is a way to define a UUID primitive type in Swaggard?

I could define these as `# @attr [string] id` (which I am currently doing) but would rather use `# @attr [uuid] id` some it gives a bit more feedback as to what the ID format should be.

It mentions in the README under [primitive types](https://github.com/adrian-gomez/swaggard#primitives) "_When one of these types is given Swaggard will handle them directly instead of searching for a definition_" so I'm guessing that it is possible to add custom definitions, I'm just not sure how to go about this.

**Comment by adrian-gomez** [comment]
Right now there is no easy way of doing that, you would need to update the gem code to add support for custom "primitive" types

**Comment by schinery** [comment]
ok, if I get a chance I'll have a think and see if I can take a stab at trying to add something to do this.
