### ISSUE TITLE
Any way to limit which controllers appear as part of the API doc

### ISSUE THREAD

**Issue by ritchiey** [Moove-it/swaggard#4]
Thanks very much for writing Swaggard. I wasn't having much luck assembling the various other swagger related gems. This one worked straight out of the box.

I'm probably missing something but it seems that Swaggard will always expose documentation for everything under /app/controllers. Is there any way I could limit it so that it only generated docs for say /app/controllers/api ?

Thanks

**Comment by adrian-gomez** [comment]
Hi, great to know it's working for you!

You can definitely do that:

```
# config/initializers/swaggard.rb
Swaggard.configure do |config|
  ...
  config.controllers_path = "#{Rails.root}/app/controllers/api/**/*.rb"
  ...
end
```

I have also updated the README to include this information.

Hope this helps.

**Comment by ritchiey** [comment]
Perfect. Thanks, very much.
