### ISSUE TITLE
https failing

### ISSUE THREAD

**Issue by michaelreynolds** [Moove-it/swaggard#7]
As seen in issue https://github.com/swagger-api/swagger-ui/issues/1957

Is there a way to change is in the implementation of swagger-ui?

**Comment by adrian-gomez** [comment]
@michaelreynolds this is probably to late (sorry about that) but here it goes anyways, we have recently updated to the latest version of swagger-ui which corrects the https issue. 
So versions >= 0.4.0 should work ok
